version: '3.9'

services: 
  db:
    container_name: template_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Abcd1234!"
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - ./mssql:/var/opt/mssql/data