version: '3'

services: 
  api:
    container_name: template_api
    image: drglasdou/dotnet:api_rest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on: 
      - db
  db:
    container_name: template_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Abcd@1234"
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - mssql:/var/opt/mssql

volumes: 
  mssql:
    