name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VERSION_FILE: version.txt

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read the current version
      id: read_version
      run: echo "::set-output name=version::$(cat $VERSION_FILE)"

    - name: Increment the version
      id: increment_version
      run: echo "::set-output name=version::$(expr ${{ steps.read_version.outputs.version }} + 1)" > $VERSION_FILE

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/dotnet-rest:${{ steps.increment_version.outputs.version }}
          ${{ secrets.DOCKERHUB_USERNAME }}/dotnet-rest:latest

