on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Set environment variable for the version
      run: |
        echo "DOCKER_IMAGE_NAME=dotnet-rest" >> $GITHUB_ENV

    - name: Determine the bump level
      id: bump-level
      run: |
        commit_message=$(git log --format=%B -n 1 $GITHUB_SHA)
        if [[ $commit_message == *"change:"* ]]; then
          echo "::set-output name=bump::major"
        elif [[ $commit_message == *"feat:"* ]]; then
          echo "::set-output name=bump::minor"
        elif [[ $commit_message == *"fix:"* ]]; then
          echo "::set-output name=bump::patch"
        else
          echo "::set-output name=bump::none"
        fi
        
      if: steps.bump-level.outputs.bump != 'none'
      
    - name: Determine the new version
      id: version
      uses: PaulHatch/semantic-version@v5.3.0
      with:
        bump: ${{ steps.bump-level.outputs.bump }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.version.outputs.version }}
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
