name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read the current version
      id: read_version
      run: echo "::set-output name=version::$(cat ./version.txt)"
      
    - name: Increment the version
      id: increment_version
      run: |
        # Increment the version and save it to the environment
        NEW_VERSION=$(( ${{ steps.read_version.outputs.version }} + 1 ))
        echo "::set-output name=version::$NEW_VERSION" 
        echo "Version after increment: $NEW_VERSION" # For debugging purposes
        echo "$NEW_VERSION" > ./version.txt  # Overwrite version.txt with the new version

    - name: Set environment variable for the version
      run: |
        echo "VERSION=${{ steps.increment_version.outputs.version }}" >> $GITHUB_ENV
        echo "DOCKER_IMAGE_NAME=dotnet-rest" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.VERSION }}
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          
